baseURL = "http://www.lanhuzi.com/"
defaultContentLanguage = "zh-cn"                             # en / zh-cn / ... (This field determines which i18n file to use)
title = "蓝胡子"
theme = "beautifulhugo"

pygmentsCodeFences = true
pygmentsUseClasses = true

