baseURL = "http://www.lanhuzi.com/"
defaultContentLanguage = "zh-cn"                            
title = "蓝胡子"
theme = "beg"

pygmentsCodeFences = true
pygmentsUseClasses = true

googleAnalytics = "UA-129516066-1" # Optional
disqusShortname = "lanhuzi"

[params]
  dateformat = "Jan 2, 2006" # Optional
