baseurl = "https://lanhuzi.com/"
googleAnalytics = "" # Optional
languageCode = "zh_CN" #语言
title = "蓝胡子" #博客标题
paginate = 10 #分页每页记录数
DisqusShortname = "lanhuzi" #评论时显示的名字
Copyright = "All rights reserved - 2017" #版权
canonifyurls = true 
theme = "hugo_theme_beg"
[params]
  author = "蓝胡子" #文章作者
  githubName = "semgilo" #github用户名
  dateformat = "Jan 2, 2006" # Optional
  

[[menu.main]] #页面菜单参数
  name = "蓝胡子"
  weight = -120
  identifier = "blog"
  url = "/"

[[menu.main]]
  name = "About me"
  weight = -110
  identifier = "about"
  url = "/about"
